const promise = new Promise((resolve, reject) => {
    
});

promise.then((value) => {

}).catch(error => {

}).finally(() => {

});